data_paths:
  raw_data: '../data/AmesHousing.csv'
  X_test: '../data/X_test_scaled.csv'
  y_test: '../data/y_test.csv'

model_output_paths:
  dir: '../models'
  model: '../models/lightgbm.joblib'
  scaler: '../models/lightgbm_scaler.joblib'

cols_to_fill:
  categorical: ['Pool QC', 'Misc Feature', 'Alley', 'Fence', 'Mas Vnr Type', 'Fireplace Qu', 'Garage Cond', 'Garage Finish', 'Garage Qual', 'Garage Type', 'Bsmt Exposure', 'BsmtFin Type 2', 'Bsmt Qual', 'Bsmt Cond', 'BsmtFin Type 1']
  numerical: ['Garage Yr Blt', 'Mas Vnr Area', 'Bsmt Full Bath', 'Bsmt Half Bath']

feature_engineering:
  surface:
    op: 'sum'
    new: 'Total SF'
    old: ['Total Bsmt SF', '1st Flr SF', '2nd Flr SF']
  bath:
    op: 'weighted_sum'
    new: 'Total Bath'
    old: {'Full Bath': 1, 'Bsmt Full Bath': 1, 'Half Bath': 0.5, 'Bsmt Half Bath': 0.5}
  porch:
    op: 'sum'
    new: 'Total Porch'
    old: ['Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch']
  age:
    op: 'difference'
    new: 'House Age'
    minuend: 'Yr Sold'
    subtrahend: 'Year Built'
  remod:
    op: 'difference'
    new: 'Years Since Remod'
    minuend: 'Yr Sold'
    subtrahend: 'Year Remod/Add'
  was_remod:
    op: 'unequal'
    new: 'Was Remodeled'
    first_operand: 'Year Remod/Add'
    second_operand: 'Year Built'
  has_pool:
    op: 'greater_than_zero'
    new: 'Has Pool'
    operand: 'Pool Area'
  has_second_floor:
    op: 'greater_than_zero'
    new: 'Has Second Floor'
    operand: '2nd Flr SF'
  has_garage:
    op: 'greater_than_zero'
    new: 'Has Garage'
    operand: 'Garage Area'
  has_bsmt:
    op: 'greater_than_zero'
    new: 'Has Bsmt'
    operand: 'Total Bsmt SF'