data_paths:
  raw_data: '../data/AmesHousing.csv'
  X_test: '../data/X_test_scaled.csv'
  y_test: '../data/y_test.csv'

model_output_paths:
  dir: '../models'
  model: '../models/lightgbm.joblib'
  scaler: '../models/lightgbm_scaler.joblib'

ordinal_features:
  Lot Shape: ['Reg', 'IR1', 'IR2', 'IR3']
  Utilities: ['AllPub', 'NoSewr', 'NoSewa', 'ELO']
  Land Slope: ['Gtl', 'Mod', 'Sev']
  Exter Qual: ['Ex', 'Gd', 'TA', 'Fa', 'Po']
  Exter Cond: ['Ex', 'Gd', 'TA', 'Fa', 'Po']
  Foundation: ['BrkTil', 'CBlock', "PConc", 'Slab', 'Stone', 'Wood']
  Bsmt Qual: ['Ex', 'Gd', 'TA', 'Fa', 'Po']
  Bsmt Cond: ['Ex', 'Gd', 'TA', 'Fa', 'Po']
  Bsmt Exposure: ['Ex', 'Gd', 'TA', 'Fa', 'Po']
  BsmtFin Type 1: ['GLQ', 'ALQ', 'BLQ', 'Rec', 'LwQ', 'Unf', 'NA']
  BsmtFin Type 2: ['GLQ', 'ALQ', 'BLQ', 'Rec', 'LwQ', 'Unf', 'NA']
  Heating QC: ['Ex', 'Gd', 'TA', 'Fa', 'Po']
  Electrical: ['SBrkr', 'FuseA', 'FuseF', 'FuseP', 'Mix']
  Kitchen Qual: ['Ex', 'Gd', 'TA', 'Fa', 'Po']
  Functional: ['Typ', 'Min1', 'Min2', 'Mod', 'Maj1', 'Maj2', 'Sev', 'Sal']
  Fireplace Qu: ['Ex', 'Gd', 'TA', 'Fa', 'Po']
  Garage Finish: ['Fin', 'RFn', 'Unf', 'None']
  Garage Qual: ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'None']
  Garage Cond: ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'None']
  Paved Drive: ['Y', 'P', 'N']
  Pool QC: ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'None']
  Fence: ['GdPrv', 'MnPrv', 'GdWo', 'MnWw', 'None']

rare_categories:
  values: ['Neighborhood']

cols_to_fill:
  categorical: ['Pool QC', 'Misc Feature', 'Alley', 'Fence', 'Mas Vnr Type', 'Fireplace Qu', 'Garage Cond', 'Garage Finish', 'Garage Qual', 'Garage Type', 'Bsmt Exposure', 'BsmtFin Type 2', 'Bsmt Qual', 'Bsmt Cond', 'BsmtFin Type 1']
  numerical: ['Garage Yr Blt', 'Mas Vnr Area', 'Bsmt Full Bath', 'Bsmt Half Bath']

feature_engineering:
  surface:
    op: 'sum'
    new_name: 'Total SF'
    old: ['Total Bsmt SF', '1st Flr SF', '2nd Flr SF']
  bath:
    op: 'weighted_sum'
    new_name: 'Total Bath'
    old: {'Full Bath': 1, 'Bsmt Full Bath': 1, 'Half Bath': 0.5, 'Bsmt Half Bath': 0.5}
  porch:
    op: 'sum'
    new_name: 'Total Porch'
    old: ['Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch']
  age:
    op: 'difference'
    new_name: 'House Age'
    minuend: 'Yr Sold'
    subtrahend: 'Year Built'
  remod:
    op: 'difference'
    new_name: 'Years Since Remod'
    minuend: 'Yr Sold'
    subtrahend: 'Year Remod/Add'
  was_remod:
    op: 'unequal'
    new_name: 'Was Remodeled'
    first_operand: 'Year Remod/Add'
    second_operand: 'Year Built'
  has_pool:
    op: 'greater_than_zero'
    new_name: 'Has Pool'
    operand: 'Pool Area'
  has_second_floor:
    op: 'greater_than_zero'
    new_name: 'Has Second Floor'
    operand: '2nd Flr SF'
  has_garage:
    op: 'greater_than_zero'
    new_name: 'Has Garage'
    operand: 'Garage Area'
  has_bsmt:
    op: 'greater_than_zero'
    new_name: 'Has Bsmt'
    operand: 'Total Bsmt SF'